package com.demo.models;
// Generated Sep 10, 2022, 9:42:19 PM by Hibernate Tools 4.3.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Seat generated by hbm2java
 */
@Entity
@Table(name = "seat", catalog = "aptechmovies")
public class Seat implements java.io.Serializable {

	private Integer id;
	private String position;
	private boolean status;
	private Set<Ticket> tickets = new HashSet<Ticket>(0);

	public Seat() {
	}

	public Seat(String position, boolean status) {
		this.position = position;
		this.status = status;
	}

	public Seat(String position, boolean status, Set<Ticket> tickets) {
		this.position = position;
		this.status = status;
		this.tickets = tickets;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "position", nullable = false, length = 250)
	public String getPosition() {
		return this.position;
	}

	public void setPosition(String position) {
		this.position = position;
	}

	@Column(name = "status", nullable = false)
	public boolean isStatus() {
		return this.status;
	}

	public void setStatus(boolean status) {
		this.status = status;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "seat")
	public Set<Ticket> getTickets() {
		return this.tickets;
	}

	public void setTickets(Set<Ticket> tickets) {
		this.tickets = tickets;
	}

}
